#!/bin/bash

#SBATCH --partition=gpu_titanrtx_shared_course
#SBATCH --gres=gpu:1
#SBATCH --job-name=fact_bert
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=05:00:00
#SBATCH --mem=32000M
#SBATCH --output=job_outputs/slurm_array_%A.out

module purge
module load 2020
module load Python
module load Anaconda3

# Activate your environment
source /home/lgpu0139/.bashrc
source activate attention2

# Run your code
srun python bert_main_pl_experiments.py --task=sstwiki --seed=42
